version: 2

project_name: gitch

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/orzazade/gitch/cmd.Version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

homebrew_casks:
  - name: gitch
    repository:
      owner: orzazade
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Casks
    homepage: https://github.com/orzazade/gitch
    description: Git identity manager - never commit with the wrong identity again
    license: MIT
    hooks:
      post:
        install: |
          system_command "/usr/bin/xattr",
                         args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitch"]

nfpms:
  - package_name: gitch
    homepage: https://github.com/orzazade/gitch
    description: Git identity manager - never commit with the wrong identity again
    maintainer: Orkhan Rzazade
    license: MIT
    formats:
      - deb
      - rpm
      - apk

scoops:
  - name: gitch
    repository:
      owner: orzazade
      name: scoop-bucket
      branch: main
      token: "{{ .Env.SCOOP_BUCKET_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: https://github.com/orzazade/gitch
    description: Git identity manager - never commit with the wrong identity again
    license: MIT
    skip_upload: auto

# Chocolatey disabled - requires Windows runner to package
# TODO: Add separate Windows workflow for Chocolatey publishing
# chocolateys:
#   - name: gitch
#     owners: Orkhan Rzazade
#     authors: Orkhan Rzazade
#     title: gitch - Git Identity Manager
#     project_url: https://github.com/orzazade/gitch
#     url_template: "https://github.com/orzazade/gitch/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
#     copyright: 2024-2026 Orkhan Rzazade
#     license_url: https://github.com/orzazade/gitch/blob/main/LICENSE
#     require_license_acceptance: false
#     project_source_url: https://github.com/orzazade/gitch
#     docs_url: https://github.com/orzazade/gitch#readme
#     bug_tracker_url: https://github.com/orzazade/gitch/issues
#     tags: "git identity ssh gpg cli developer-tools"
#     summary: Git identity manager CLI - never commit with the wrong identity again
#     description: |
#       gitch helps you manage multiple Git identities (email, name, SSH keys, GPG keys).
#
#       Features:
#       - Switch between identities instantly
#       - Auto-switching based on repository rules
#       - SSH key management per identity
#       - GPG signing key support
#       - Shell prompt integration
#     release_notes: "https://github.com/orzazade/gitch/releases/tag/{{ .Tag }}"
#     api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
#     source_repo: "https://push.chocolatey.org/"
#     skip_publish: false
#     goamd64: v1
