version: 2

project_name: gitch

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.buildTime={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

brews:
  - repository:
      owner: orzazade
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/orzazade/gitch
    description: Git identity manager - never commit with the wrong identity again
    license: MIT
    test: |
      system "#{bin}/gitch", "--version"
    install: |
      bin.install "gitch"

nfpms:
  - package_name: gitch
    homepage: https://github.com/orzazade/gitch
    description: Git identity manager - never commit with the wrong identity again
    maintainer: Orkhan Rzazade
    license: MIT
    formats:
      - deb
      - rpm
      - apk
